version: '3.3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
#    environment:
#      - MYSQL_DATABASE=music_database_application
  musicdb:
    image: emil/mymusicdb:v1
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db